# GitHub Pages configuration
theme: jekyll-theme-midnight

# Site settings
title: My GitHub Pages Site
description: A description of my site

# Navigation links
nav:
  - title: Home
    url: /

# Plugins
plugins:
  - jekyll-feed

# Exclude files and directories
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .git

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge